
name: Clone Public Repository Workflow

on:
    push:
      tags:
        - "clone*"

jobs:
    
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone nextarter-chakra PUBLIC repository
        uses: whyakari/github-repo-action@v3.1
        with:
          depth: 1
          branch: 'main'
          owner: 'yucelz'
          repository: 'poc-nextarter-chakra'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd poc-nextarter-chakra
          ls -la

